import { Component } from '@angular/core';
import { CurrencyPipe } from '@angular/common';
import { HeaderComponent } from './components/header/header.component';
import { CourseCatalogComponent } from './components/course-catalog/course-catalog.component';
import { CourseDetailsComponent } from './components/course-details/course-details.component';
import { FooterComponent } from './components/footer/footer.component';
import { Course } from './course';

@Component({ selector: 'app-root', imports: [CurrencyPipe, HeaderComponent, CourseCatalogComponent, CourseDetailsComponent, FooterComponent], templateUrl: './app.component.html', styleUrl: './app.component.css' })
export class AppComponent {
  userLoggedIn = false; selectedCourse: Course | null = null; view: 'catalog' | 'courses' | 'admin' | 'cart' | 'checkout' = 'catalog'; checkoutDone = false; cart: Course[] = []; toast = '';
  courses: Course[] = [
    { id: 1, title: 'Fundamentos de Angular', category: 'Desenvolvimento', level: 'Iniciante', workload: '20 horas', vacancies: 12, image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80', description: 'Construa aplicações modernas conhecendo componentes, templates, eventos e diretivas do Angular.', instructor: 'Mariana Costa', certificate: true, enrolled: false, favorite: false, price: 19.9, progress: 0, handout: 'Guia completo de Angular' },
    { id: 2, title: 'Design de Interfaces', category: 'Design', level: 'Intermediário', workload: '16 horas', vacancies: 5, image: 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=900&q=80', description: 'Aprenda a criar interfaces acessíveis, agradáveis e centradas nas pessoas usuárias.', instructor: 'Rafael Nunes', certificate: true, enrolled: false, favorite: false, price: 17.9, progress: 0, handout: 'Workbook completo de UI Design' },
    { id: 3, title: 'Lógica de Programação', category: 'Tecnologia', level: 'Iniciante', workload: '12 horas', vacancies: 8, image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80', description: 'Desenvolva o raciocínio necessário para resolver problemas e escrever seus primeiros algoritmos.', instructor: 'Lucas Martins', certificate: true, enrolled: true, favorite: true, price: 14.9, progress: 42, handout: 'Apostila completa de algoritmos' }
  ];

  get total(): number { return this.cart.reduce((sum, course) => sum + course.price, 0); }
  get enrolledCourses(): Course[] { return this.courses.filter(course => course.enrolled); }
  toggleLogin(): void { this.userLoggedIn = !this.userLoggedIn; this.notify(this.userLoggedIn ? 'Conta fictícia conectada: Ana Souza' : 'Você saiu da conta de demonstração.'); }
  navigate(view: 'catalog' | 'courses' | 'admin' | 'cart'): void { if ((view === 'courses' || view === 'admin') && !this.userLoggedIn) { this.userLoggedIn = true; this.notify('Conta de demonstração conectada para acessar esta área.'); } this.view = view; this.checkoutDone = false; window.scrollTo({ top: 0, behavior: 'smooth' }); }
  selectCourse(course: Course): void { this.selectedCourse = course; }
  toggleFavorite(course: Course): void { course.favorite = !course.favorite; }
  addToCart(course: Course): void { if (course.enrolled) { this.navigate('courses'); return; } if (!this.cart.some(item => item.id === course.id)) { this.cart.push(course); this.notify(`${course.title} foi adicionado ao carrinho.`); } else { this.notify('Este curso já está no carrinho.'); } }
  removeFromCart(course: Course): void { this.cart = this.cart.filter(item => item.id !== course.id); }
  checkout(): void { if (!this.cart.length) return; this.cart.forEach(course => { course.enrolled = true; course.progress = 0; course.vacancies = Math.max(0, course.vacancies - 1); }); this.cart = []; this.checkoutDone = true; this.view = 'checkout'; }
  downloadHandout(course: Course): void { const content = `APRENDE+ | MATERIAL DE APOIO\n${course.handout.toUpperCase()}\n\nCURSO: ${course.title}\nINSTRUTOR(A): ${course.instructor}\nCARGA HORÁRIA: ${course.workload}\nNÍVEL: ${course.level}\n\nSUMÁRIO\n1. Como usar este material\n2. Objetivos de aprendizagem\n3. Fundamentos e conceitos-chave\n4. Roteiro prático de estudo\n5. Exercícios de fixação\n6. Checklist final\n\n1. COMO USAR ESTE MATERIAL\nReserve blocos curtos de estudo, faça anotações com suas próprias palavras e pratique após cada módulo. Use esta apostila como guia de revisão durante todo o curso.\n\n2. OBJETIVOS DE APRENDIZAGEM\n• Compreender os conceitos essenciais da formação.\n• Aplicar os conhecimentos em pequenos desafios.\n• Construir um projeto prático para o portfólio.\n• Identificar os próximos temas para aprofundamento.\n\n3. FUNDAMENTOS E CONCEITOS-CHAVE\nComece pelo problema que você quer resolver. Divida tarefas grandes em etapas menores, valide cada etapa e mantenha um registro do que aprendeu. Em ${course.title}, teoria e prática devem caminhar juntas: observe exemplos, adapte-os e crie uma versão própria.\n\n4. ROTEIRO PRÁTICO DE ESTUDO\nSemana 1 — Leia os módulos iniciais e anote 5 conceitos novos.\nSemana 2 — Reproduza os exemplos e altere pelo menos um detalhe em cada um.\nSemana 3 — Resolva um desafio autoral simples.\nSemana 4 — Revise, organize o projeto e compartilhe seu resultado.\n\n5. EXERCÍCIOS DE FIXAÇÃO\n1. Explique o principal conceito desta unidade em três frases.\n2. Crie um exemplo prático que use esse conceito.\n3. O que você melhoraria no seu primeiro resultado?\n4. Escolha uma dificuldade encontrada e descreva como a resolveria.\n\n6. CHECKLIST FINAL\n[ ] Concluí as aulas do módulo.\n[ ] Fiz anotações e pratiquei.\n[ ] Resolvi os exercícios.\n[ ] Salvei meu projeto ou atividade.\n[ ] Sei qual será meu próximo passo.\n\nBom estudo! Este material foi preparado para a experiência demonstrativa da Aprende+.`; const blob = new Blob([content], { type: 'text/plain;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${course.handout.toLowerCase().replace(/[^a-z0-9]+/gi, '-')}.txt`; link.click(); URL.revokeObjectURL(link.href); }
  addTestCourse(): void { const id = Math.max(...this.courses.map(course => course.id)) + 1; this.courses.push({ id, title: 'Novo curso de teste', category: 'Administração', level: 'Iniciante', workload: '8 horas', vacancies: 20, image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=900&q=80', description: 'Curso criado na área administrativa de demonstração.', instructor: 'Equipe Aprende+', certificate: true, enrolled: false, favorite: false, price: 9.9, progress: 0, handout: 'Apostila completa do curso de teste' }); this.notify('Novo curso de teste publicado no catálogo.'); }
  notify(message: string): void { this.toast = message; window.setTimeout(() => this.toast = '', 2800); }
}
